export const SIDE_BAR_TOGGLE = "SIDE_BAR_TOGGLE";
export const SIDE_CART_TOGGLE = "SIDE_CART_TOGGLE";

export const SET_PRODUCTS = "SET_PRODUCTS";
export const ADD_TO_CART = "ADD_TO_CART";
export const SET_SINGLE_PRODUCT = "SET_SINGLE_PRODUCT";
