export enum UiType {
  IS_ADMIN = "IS_ADMIN",
  IS_USER = "IS_USER",

  SIDE_BAR_TOGGLE = "SIDE_BAR_TOGGLE",

  SIDE_CART_TOGGLE = "SIDE_CART_TOGGLE",

  OPEN_PUBLIC_DRAWER = "OPEN_PUBLIC_DRAWER",
  CLOSE_PUBLIC_DRAWER = "CLOSE_PUBLIC_DRAWER",

  OPEN_ADMIN_DRAWER = "OPEN_ADMIN_DRAWER",
  CLOSE_ADMIN_DRAWER = "CLOSE_ADMIN_DRAWER",
}
